In [4]:
import cv2
import numpy as np

img = np.zeros((600, 800, 3), np.uint8)

print(img[:10])
print(len(img))

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
600


In [5]:
import cv2
import numpy as np

img = np.full((600, 800, 3), (255, 0, 255), dtype=np.uint8)

print(img[:10])
print(len(img))

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 ...

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]]
600


In [7]:
import cv2
import numpy as np

img = np.full((600, 800, 3), (255, 255, 255), dtype=np.uint8)
cv2.rectangle(img, (30, 30), (300, 300), (0, 0, 0), 3, cv2.LINE_AA)

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
import cv2
import numpy as np

width = 1000
height = 1000

img = np.full((width, height, 3), (255, 255, 255), dtype=np.uint8)
img_name = "image"

# a/b 를 수행 할때 무조건 실수형 자료형이 반환된다.
# a//b 를 사용해야 정수형으로 사용 가능하다.
cv2.circle(img, (width//2, height//2), 135, (255, 0, 255), 3, cv2.LINE_AA)

print(type(width))


"""
cv2.ellipse(img, (width/2, height/2), (120, 120), 0, 0, 160, (255, 0, 0), 2, cv2.LINE_AA)
cv2.ellipse(img, (width/2, height/2), (130, 130), 180, 0, 160, (0, 0, 255), 2, cv2.LINE_AA)
cv2.ellipse(img, (width/2, height/2), (180, 100), 0, 0, 360, (0, 0, 0), 2, cv2.LINE_AA)
"""
cv2.imshow(img_name, img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'int'>


In [25]:
import socket

print("1.소켓생성")
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

print("3.접속시도")
sock.connect(("211.109.220.211", 8554))

print("5.데이터 송신")
sock.sendall(bytes("Hello socket", "utf-8"))

print("6.접속 종료")
sock.close()

1.소켓생성
3.접속시도
5.데이터 송신
6.접속 종료


In [29]:
import cv2
import numpy as np

def onMouse(event,x,y,flags,param):

    # x, y 마우스 클릭지점 
    if event==cv2.EVENT_LBUTTONDOWN: # 마우스 왼쪽 버튼 클릭
        cv2.rectangle(param[0],(x-5,y-5),(x+5,y+5),(255,0,0))
    cv2.imshow('img',param[0])

width = 1000
height = 1000

img = np.full((width, height, 3), (255, 255, 255), dtype=np.uint8)
cv2.circle(img, (width//2, height//2), 135, (255, 0, 255), 3, cv2.LINE_AA)

cv2.imshow('img',img)
cv2.setMouseCallback('img',onMouse,[img])
cv2.waitKey()
cv2.destroyAllWindows()