In [4]:
import cv2
import numpy as np

img = np.zeros((600, 800, 3), np.uint8)

print(img[:10])
print(len(img))

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
600


In [5]:
import cv2
import numpy as np

img = np.full((600, 800, 3), (255, 0, 255), dtype=np.uint8)

print(img[:10])
print(len(img))

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 ...

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]

 [[255   0 255]
  [255   0 255]
  [255   0 255]
  ...
  [255   0 255]
  [255   0 255]
  [255   0 255]]]
600


In [7]:
import cv2
import numpy as np

img = np.full((600, 800, 3), (255, 255, 255), dtype=np.uint8)
cv2.rectangle(img, (30, 30), (300, 300), (0, 0, 0), 3, cv2.LINE_AA)

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import cv2
import numpy as np
import math

class MapCircle:
    def __init__(self, center, radius, color):
        self.center = center
        self.radius = radius
        self.color = color

    def circle(self,img):
        cv2.circle(img, self.center, self.radius,
                   self.color, -1)

    # 중심점 과 point 사이의 거리를 측정하여 원의 내부에 존재시 True
    def is_circle(self,point):
        center_x_pos = self.center[1]
        center_y_pos = self.conter[2]

        click_x_pos = point[1]
        click_y_pos = point[2]

        interval_two_points = math.sqrt(math.pow(center_x_pos - click_x_pos, 2) +
                           math.pow(center_y_pos - center_y_pos, 2))

        print("두점 사이의 거리", interval_two_points)

        return interval_two_points

    def __del__(self):
        print("객체소멸")


a = MapCircle((100, 100), 10, (0, 0, 255))

print(type(MapCircle))

width = 1000
height = 1000

img = np.full((width, height, 3), (255, 255, 255), dtype=np.uint8)
a.circle(img)
img_name = "image"

print("원의 중심점", a.center)
print("원의 반지름", a.radius)
print("원의 색상",   a.color)

# a/b 를 수행 할때 무조건 실수형 자료형이 반환된다.
# a//b 를 사용해야 정수형으로 사용 가능하다.
# cv2.circle(img, MapCircle.center, MapCircle.radius, MapCircle.color, -1, cv2.LINE_AA)

cv2.imshow(img_name, img)
cv2.waitKey(0)
cv2.destroyAllWindows()

객체소멸
<class 'type'>
원의 중심점 (100, 100)
원의 반지름 10
원의 색상 (0, 0, 255)


In [23]:
import socket

print("1.소켓생성")
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

print("3.접속시도")
sock.connect(("211.109.220.211", 8554))

print("5.데이터 송신")
sock.sendall(bytes("Hello socket", "utf-8"))

print("6.접속 종료")
sock.close()

1.소켓생성
3.접속시도


TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

In [22]:
import cv2
import numpy as np
import math

############################  variables  ############################
screen_width = 500
screen_height = 500

circle_interval_x_pos = screen_width//10
circle_interval_y_pos = screen_height//10

circle_center_x_pos = circle_interval_x_pos
circle_center_y_pos = circle_interval_y_pos

circle_radius = screen_width//100

### color variable ###
RED = [0,0,255]
GREEN = [0, 255, 0]
BLUE = [255, 0, 0]
YELLOW = [0,255,255]
BLACK = [0,0,0]
### color variable ###
############################  variables  ############################

class MapCircle:
    def __init__(self, center, radius, color):
        self.center = center
        self.radius = radius
        self.color = color

    def circle(self, img):
        cv2.circle(img, self.center, self.radius,
                   self.color, -1)

    # 중심점 과 point 사이의 거리를 측정
    def circle_dis(self, point):
        center_x_pos = self.center[0]
        center_y_pos = self.center[1]

        click_x_pos = point[0]
        click_y_pos = point[1]

        interval_two_points = math.sqrt(math.pow(center_x_pos - click_x_pos, 2) +
                                        math.pow(center_y_pos - click_y_pos, 2))

        return int(interval_two_points)

    def __del__(self):
        print("remove")

def onMouse(event,x,y,flags,param):

    # x, y 마우스 클릭지점 
    if event==cv2.EVENT_LBUTTONDOWN: # 마우스 왼쪽 버튼 클릭
        circle_dis = []
        print(x, y)

        # 거리비교
        i = 0
        while i < max:
            circle_dis.append(circles[i].circle_dis((x, y)))
            i += 1
        min_index = circle_dis.index(min(circle_dis))
        
        # 색상비교 알고리즘
        i = 0
        while i < max:
            if i == min_index:
                if circles[min_index].color == RED:
                    circles[min_index].color = BLUE
                else:
                    circles[min_index].color = BLUE

            else:
                circles[i].color = RED
            i += 1


        i = 0
        while i < max:
            circles[i].circle(param[0])
            i += 1 

    if event==cv2.EVENT_RBUTTONDOWN:
        i = 0
        circle_dis = []
        print(x, y)

        while i < max:
            circle_dis.append(circles[i].circle_dis((x, y)))
            i += 1
        min_index = circle_dis.index(min(circle_dis))

        if circles[min_index].color == RED:
            circles[min_index].color = GREEN
        else:
            circles[min_index].color = RED

        i = 0
        while i < max:
            circles[i].circle(param[0])
            i += 1

    cv2.imshow('img',param[0])

circles = [] 

img = np.full((screen_width, screen_height, 3), (255, 255, 255), dtype=np.uint8)

while circle_center_x_pos < screen_width:
    circle_center_y_pos = circle_interval_y_pos

    while circle_center_y_pos < screen_height:
        circles.append(MapCircle(
            (circle_center_x_pos, circle_center_y_pos), circle_radius, RED))
        circle_center_y_pos += circle_interval_y_pos

    circle_center_x_pos += circle_interval_x_pos


max = len(circles)
print(max)

i = 0
while i < max :
    circles[i].circle(img)
    i += 1


#픽셀값을 모두 저장해 놓은 상태 
#pixcel = np.array(img)

cv2.imshow('img',img)
cv2.setMouseCallback('img',onMouse,[img])
cv2.waitKey()
cv2.destroyAllWindows()

remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
remove
81
201 98
204 142
247 111
259 156
252 207
316 212
298 166
252 192
250 166
284 202
286 127
226 200
228 139
273 191
327 196
323 131
241 191
260 231
236 141
288 182
230 193
249 139
311 155
310 201
255 195
250 153
199 207
190 159
281 225
106 222
149 151
172 197
256 148
251 199
283 203
291 259
357 254
364 306
406 295
425 368
251 151
251 195
297 205
304 251
350 252
353 296
407 295
392 334
291 201
303 196
299 199
334 302
322 236
339 285

KeyboardInterrupt: 